// svelte-calc/src/lib/btn.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	export let value: any;
	const dispatch = createEventDispatcher();
	function ping() {
		dispatch('ping', value);
	}
</script>

<button on:click={ping}>{value}</button>

<style>
	button {
		cursor: pointer;
		margin: 5px 2%;
		width: 18%;
	}
</style>

// ng-calc/src/app/btn/btn.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-btn',
  standalone: true,
  imports: [CommonModule],
  template: ` <button (click)="ping.emit(value)">{{ value }}</button> `,
  styles: [
    `
      button {
        cursor: pointer;
        margin: 5px 2%;
        width: 18%;
      }
    `,
  ],
})
export class BtnComponent {
  @Input() value: string = '';
  @Output() ping = new EventEmitter<string>();
}
